using System.IO.Abstractions;
using QuicPeer;
using QuicPeer.AppCommands;
using QuicPeer.Client;
using QuicPeer.Client.Abstraction;
using QuicPeer.Logging;
using QuicPeer.Options;
using QuicPeer.Server;
using QuicPeer.Common;
using QuicPeer.Common.Messaging;
using QuicPeer.Common.Messaging.ClientQueue;
using QuicPeer.Common.Messaging.ServerQueue;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddSerilogLogging();
builder.Services.AddHostedService<PeerServer>();
builder.Services.AddSingleton<ConsoleApp>();
builder.Services.AddScoped<IPeerConnector, PeerConnector>();
builder.Services.AddSingleton<IPeerClientFactory, PeerClientFactory>();
builder.Services.AddAppCommands();
builder.Services.AddSingleton<IConsoleAccessor, ConsoleAccessor>();
builder.Services.AddSingleton<IChecksumProvider, ChecksumProvider>();
builder.Services.AddScoped<IFilesReceiver, FilesReceiver>();
builder.Services.AddScoped<ConnectionManager>();
builder.Services.AddSingleton<IFileSystem>(new FileSystem());
builder.Services.AddSingleton<IMessageQueue<IServerMessage>, ServerMessageQueue>();
builder.Services.AddSingleton<IMessageQueue<IClientMessage>, ClientMessageQueue>();
builder.Services.AddSingleton<IPeersStore, PeersStore>();
builder.ConfigureOptions();

var server = builder.Build();
await server.StartAsync();
var consoleApp = server.Services.GetRequiredService<ConsoleApp>();
await consoleApp.StartAsync(CancellationToken.None);
await server.WaitForShutdownAsync();